version: "3.8"
services:
  example-mongodb:
    container_name: example-mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      # - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./backup-mongo:/backup-mongo
      - ./db:/data/db

    networks:
      - backup-restore-mongodb-network

networks:
  backup-restore-mongodb-network:
    external: true
    name: backup-restore-mongodb-network